"""Draw the four charts the README shows, from the data the site already reads.

**Run once, commit the output, never run in CI.** Same arrangement as
`scripts/make_basemap.py` and `scripts/make_social_card.py`: a static asset
generated by a script that is not part of the build. This one needs only the
standard library, so `requirements.txt` stays at seven packages either way.

    python scripts/make_readme_charts.py

**Why the README gets its own drawing code rather than reusing `src/charts.py`.**
Plotly writes JSON for a browser to render and GitHub renders no JavaScript, so a
README chart has to be static SVG. Nothing here is recomputed and no number is
typed: every figure is read from `web/public/data/*.json`, which
`src/app_export.py` writes by calling the same functions the Plotly figures call.

**Unlike the other two committed-asset scripts, this one is guarded.**
`make_social_card.py` says "re-run it only if the hero numbers change", which is a
manual step nothing checks, and this repo has found that shape of failure four
times. `tests/test_readme_assets.py` rebuilds every SVG in memory and asserts byte
equality against what is committed, so a moved number fails the build instead of
ageing on the front page.

**Light and dark pairs, not one self-theming file.** An SVG loaded through an
`<img>` resolves `prefers-color-scheme` against the operating system, not against
GitHub's own theme toggle, so a single file with a media query inside it
mismatches for any reader whose two settings disagree. `<picture>` with a dark
`<source>` is what GitHub documents, so that is what the README uses. Backgrounds
are transparent, which is why the pair is needed and also why neither variant
shows a hard-edged white box against the page.

**House rules from `src/charts.py` are carried over on purpose**, because they are
the project's identity rather than a styling preference: one red subject per
chart, everything else grey, minimal rules, and titles that state the takeaway
rather than the topic. Every number in a title or a subtitle is formatted from the
data rather than typed, which is gotcha 76.

**Red is `#CC0000` on light and `#EE3224` on dark.** Both are house colours, the
primary and the accent. Primary red on a dark canvas reads as brown.

**`#E6E6E6` is a bar fill and never a line or a small mark**, which is gotcha 53.
The two grey series on the slope chart are drawn in the muted ink, not the fill,
because a 2px `#E6E6E6` stroke on white is invisible.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "web" / "public" / "data"
OUT = ROOT / ".github" / "assets"

W = 880
PAD = 32

SERIF = "'IBM Plex Serif', Georgia, 'Times New Roman', serif"
SANS = "'IBM Plex Sans', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif"

THEMES = {
    "light": {"ink": "#1A1A1A", "muted": "#6B6B6B", "rule": "#E6E6E6",
              "fill": "#E6E6E6", "red": "#CC0000"},
    "dark": {"ink": "#E6EDF3", "muted": "#8B949E", "rule": "#30363D",
             "fill": "#30363D", "red": "#EE3224"},
}

SOURCE_DGCA = "Source: DGCA traffic statistics, pulled 2026-08-15. Computed in-repo, not quoted."


# ---------------------------------------------------------------------------
# SVG primitives. Deliberately tiny: four charts do not justify a chart layer.
# ---------------------------------------------------------------------------

def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def wrap(text_in: str, width: int) -> list[str]:
    """Break on spaces. SVG has no auto-wrap and a title runs to two lines."""
    lines: list[str] = []
    line_so_far = ""
    for word in text_in.split(" "):
        candidate = f"{line_so_far} {word}".strip()
        if len(candidate) > width and line_so_far:
            lines.append(line_so_far)
            line_so_far = word
        else:
            line_so_far = candidate
    if line_so_far:
        lines.append(line_so_far)
    return lines


def text(x: float, y: float, s: str, *, size: float, fill: str, family: str = SANS,
         weight: str = "400", anchor: str = "start") -> str:
    return (
        f'<text x="{x:g}" y="{y:g}" font-family="{family}" font-size="{size:g}" '
        f'font-weight="{weight}" fill="{fill}" text-anchor="{anchor}">{esc(s)}</text>'
    )


def rect(x: float, y: float, w: float, h: float, fill: str) -> str:
    return f'<rect x="{x:g}" y="{y:g}" width="{max(w, 0.0):g}" height="{h:g}" fill="{fill}"/>'


def line(x1: float, y1: float, x2: float, y2: float, stroke: str, width: float = 1) -> str:
    return (
        f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" '
        f'stroke="{stroke}" stroke-width="{width:g}"/>'
    )


def polyline(points: list[tuple[float, float]], stroke: str, width: float) -> str:
    pts = " ".join(f"{x:.2f},{y:.2f}" for x, y in points)
    return (
        f'<polyline points="{pts}" fill="none" stroke="{stroke}" stroke-width="{width:g}" '
        f'stroke-linecap="round" stroke-linejoin="round"/>'
    )


def head(t: dict, title: str, subtitle: str) -> tuple[list[str], float]:
    """Takeaway title, then a subtitle carrying the unit, the year and the basis."""
    parts: list[str] = []
    y = 34.0
    for ln in wrap(title, 74):
        parts.append(text(PAD, y, ln, size=20, fill=t["ink"], family=SERIF, weight="600"))
        y += 26
    y += 2
    for ln in wrap(subtitle, 112):
        parts.append(text(PAD, y, ln, size=13, fill=t["muted"]))
        y += 18
    return parts, y + 16


def foot(t: dict, y: float, source: str) -> list[str]:
    return [text(PAD, y, source, size=11, fill=t["muted"])]


def svg(height: float, body: list[str], alt: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{height:g}" '
        f'viewBox="0 0 {W} {height:g}" role="img" aria-label="{esc(alt)}">\n'
        + "\n".join(body)
        + "\n</svg>\n"
    )


def _load(name: str):
    return json.loads((DATA / f"{name}.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# 1. The answer. Yield headroom by corridor, against the traffic each carries.
# ---------------------------------------------------------------------------

def chart_answer_headroom(t: dict) -> str:
    rows = [r for r in _load("corridors") if r.get("yield_headroom_pct") is not None]
    rows.sort(key=lambda r: -r["yield_headroom_pct"])
    gulf = next(r for r in rows if r["region"] == "Gulf")

    title = ("The corridor carrying half of India's international traffic is the one with "
             "no room left to earn its cost")
    subtitle = ("Yield headroom by corridor, per cent, against IndiGo's achieved 5.06 INR per "
                "RPK at the 81% load factor Indian carriers fly internationally. Positive "
                "means the corridor clears its unit cost with room to spare.")
    body, top = head(t, title, subtitle)

    x0, x1 = 214.0, 656.0
    row_h, bar_h = 34.0, 17.0
    lo, hi = -8.0, 36.0

    def px(v: float) -> float:
        return x0 + (v - lo) / (hi - lo) * (x1 - x0)

    zero = px(0.0)
    body.append(line(zero, top - 8, zero, top + len(rows) * row_h + 2, t["rule"]))

    for i, r in enumerate(rows):
        cy = top + i * row_h
        v = r["yield_headroom_pct"]
        is_gulf = r["region"] == "Gulf"
        end = px(v)
        body.append(rect(min(zero, end), cy, abs(end - zero), bar_h, t["red"] if is_gulf else t["fill"]))
        body.append(text(PAD, cy + 13, r["region"], size=13,
                         fill=t["ink"] if is_gulf else t["muted"],
                         weight="600" if is_gulf else "400"))
        body.append(text(end + (8 if v >= 0 else -8), cy + 13, f"{v:+.1f}%", size=13,
                         fill=t["red"] if is_gulf else t["ink"],
                         weight="600" if is_gulf else "400",
                         anchor="start" if v >= 0 else "end"))
        body.append(text(W - PAD, cy + 13, f"{r['share_pct']:.1f}% of traffic",
                         size=12, fill=t["muted"], anchor="end"))

    y = top + len(rows) * row_h + 34
    body.append(text(PAD, y, (
        f"The Gulf is {gulf['share_pct']:.1f}% of the market on {gulf['yield_headroom_pct']:+.1f}% "
        f"of headroom. Europe and North America are where the aircraft cover their cost."
    ), size=13, fill=t["ink"], weight="600"))
    body += foot(t, y + 30, SOURCE_DGCA)
    return svg(y + 48, body, title)


# ---------------------------------------------------------------------------
# 2. The finding in two numbers. More passengers, half the distance.
# ---------------------------------------------------------------------------

def chart_stage_gap(t: dict) -> str:
    intl = {r["airline"]: r for r in _load("carriers")["international_summary"]}
    indigo, air_india = intl["IndiGo"], intl["Air India"]
    ratio = air_india["stage_length_km"] / indigo["stage_length_km"]

    title = "IndiGo flies more international passengers than Air India, over half the distance"
    subtitle = ("Indian carriers' international operations, 2025. IndiGo is the highlighted "
                "subject in both panels because the finding is the pair, not either measure "
                "on its own.")
    body, top = head(t, title, subtitle)

    panels = (
        ("INTERNATIONAL PASSENGERS", "pax", 1e6, "{:.1f}M", PAD, 404.0),
        ("AVERAGE STAGE LENGTH", "stage_length_km", 1.0, "{:,.0f} km", 476.0, float(W - PAD)),
    )
    bar_h, gap = 30.0, 48.0

    for label, key, divisor, fmt, px0, px1 in panels:
        body.append(text(px0, top, label, size=11, fill=t["muted"], weight="600"))
        body.append(line(px0, top + 11, px1, top + 11, t["rule"]))
        biggest = max(indigo[key], air_india[key])
        avail = px1 - px0 - 78 - 88
        for j, (name, row) in enumerate((("IndiGo", indigo), ("Air India", air_india))):
            cy = top + 36 + j * gap
            width = row[key] / biggest * avail
            body.append(text(px0, cy + 20, name, size=13,
                             fill=t["ink"] if name == "IndiGo" else t["muted"],
                             weight="600" if name == "IndiGo" else "400"))
            body.append(rect(px0 + 78, cy, width, bar_h, t["red"] if name == "IndiGo" else t["fill"]))
            body.append(text(px0 + 78 + width + 9, cy + 20, fmt.format(row[key] / divisor),
                             size=13, fill=t["ink"], weight="600"))

    y = top + 36 + 2 * gap + 26
    body.append(text(PAD, y, (
        f"Air India's average international flight is {ratio:.1f} times IndiGo's. IndiGo is not "
        f"losing long-haul, it has never had the aircraft to fly it."
    ), size=13, fill=t["ink"], weight="600"))
    body += foot(t, y + 30, SOURCE_DGCA)
    return svg(y + 48, body, title)


# ---------------------------------------------------------------------------
# 3. The order book as aircraft rather than as ASK.
# ---------------------------------------------------------------------------

PLANE = ("M12 1.6 L13.3 8.2 L22.4 14.1 L22.4 16.2 L13.3 13.5 L13.3 19.2 L16.2 21.7 "
         "L16.2 22.8 L12 21.5 L7.8 22.8 L7.8 21.7 L10.7 19.2 L10.7 13.5 L1.6 16.2 "
         "L1.6 14.1 L10.7 8.2 Z")


def chart_order_book(t: dict) -> str:
    fleet = _load("order_book_fleet")
    total = fleet["total_aircraft"]
    needed = fleet["needed_to_hold_share"]
    surplus = fleet["surplus"]
    ratio = fleet["book_vs_growth_ratio"]
    operators = ", ".join(f"{o['count']} {o['operator']}" for o in fleet["by_operator"])
    indian_share = next(
        r["share_pct"] for r in _load("carriers")["who_carries_india"]
        if r["carrier_group"] == "Indian"
    )

    title = (f"{total} wide-bodies are on firm order and {surplus} of them have nowhere to go "
             f"at today's stage lengths")
    subtitle = (f"One aeroplane, one glyph. {operators}. The book converts to {ratio:.2f} times "
                f"the capacity growth Indian carriers need to hold their {indian_share:.1f}% "
                f"share, so the question is where the surplus flies, not whether it exists.")
    body, top = head(t, title, subtitle)

    cols, col_w, row_h, scale = 20, 42.0, 44.0, 1.15
    for i in range(total):
        gx = PAD + (i % cols) * col_w
        gy = top + (i // cols) * row_h
        body.append(
            f'<path d="{PLANE}" fill="{t["fill"] if i < needed else t["red"]}" '
            f'transform="translate({gx:g} {gy:g}) scale({scale:g})"/>'
        )

    y = top + (-(-total // cols)) * row_h + 22
    legend = (
        (needed, "needed to hold share at today's sector length", t["fill"], False),
        (surplus, "surplus to it, and the reason this case exists", t["red"], True),
    )
    for count, label, colour, emphasis in legend:
        body.append(rect(PAD, y - 11, 13, 13, colour))
        body.append(text(PAD + 22, y, f"{count}   {label}", size=13,
                         fill=t["ink"] if emphasis else t["muted"],
                         weight="600" if emphasis else "400"))
        y += 25

    body += foot(t, y + 12, "Source: Airbus and Boeing order books and airport planning manuals; "
                            "the capacity need is computed from DGCA. Pulled 2026-08-15.")
    return svg(y + 30, body, title)


# ---------------------------------------------------------------------------
# 4. The premise this project reversed.
# ---------------------------------------------------------------------------

def chart_share_reversal(t: dict) -> str:
    trend = [r for r in _load("carriers")["share_trend"] if r["year"] not in (2020, 2021)]
    first, last = trend[0], trend[-1]
    gained = last["Indian"] - first["Indian"]
    lost = first["Gulf"] - last["Gulf"]

    title = (f"Indian carriers took {gained:.1f} points of their own international market back "
             f"while Gulf carriers gave up {lost:.1f}")
    subtitle = (f"Share of India international sector passengers by carrier home region, per "
                f"cent, {first['year']} to {last['year']}. 2020 and 2021 are omitted: "
                f"repatriation flying distorts them beyond use.")
    body, top = head(t, title, subtitle)

    x0, x1 = PAD + 40, 664.0
    plot_h, lo, hi = 236.0, 20.0, 50.0

    def px(year: int) -> float:
        return x0 + (year - first["year"]) / (last["year"] - first["year"]) * (x1 - x0)

    def py(v: float) -> float:
        return top + plot_h - (v - lo) / (hi - lo) * plot_h

    for tick in (20, 30, 40, 50):
        body.append(line(x0 - 12, py(tick), x1, py(tick), t["rule"]))
        body.append(text(x0 - 18, py(tick) + 4, f"{tick}%", size=11, fill=t["muted"], anchor="end"))

    for name in ("Other foreign", "Gulf", "Indian"):
        highlight = name == "Indian"
        # The muted ink, never the bar fill: a 2px #E6E6E6 stroke on white is
        # invisible, which is gotcha 53 in its line-mark form.
        colour = t["red"] if highlight else t["muted"]
        # Two segments. The omitted pandemic years are a gap in the record, and
        # drawing through them would assert a path nobody measured.
        for lo_y, hi_y in ((2015, 2019), (2022, 2025)):
            body.append(polyline(
                [(px(r["year"]), py(r[name])) for r in trend if lo_y <= r["year"] <= hi_y],
                colour, 3.0 if highlight else 2.0,
            ))
        body.append(text(x1 + 12, py(last[name]) + 4, f"{name} {last[name]:.1f}%", size=12,
                         fill=colour, weight="600" if highlight else "400"))

    for year in (first["year"], last["year"]):
        body.append(text(px(year), top + plot_h + 24, str(year), size=12,
                         fill=t["muted"], anchor="middle"))

    y = top + plot_h + 56
    body.append(text(PAD, y, (
        "This reversed the case's opening premise. The share taken back is short-haul, which "
        "is exactly where the aircraft already reach."
    ), size=13, fill=t["ink"], weight="600"))
    body += foot(t, y + 30, SOURCE_DGCA)
    return svg(y + 48, body, title)


CHARTS = {
    "answer_headroom": chart_answer_headroom,
    "stage_gap": chart_stage_gap,
    "order_book": chart_order_book,
    "share_reversal": chart_share_reversal,
}


def build() -> dict[str, str]:
    """Every SVG, keyed by filename. `tests/test_readme_assets.py` compares bytes."""
    out: dict[str, str] = {}
    for name, fn in CHARTS.items():
        for variant, theme in THEMES.items():
            out[f"{name}-{variant}.svg"] = fn(theme)
    return out


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for filename, markup in build().items():
        (OUT / filename).write_text(markup, encoding="utf-8", newline="\n")
        print(f"  wrote .github/assets/{filename}  ({len(markup):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
