"""Build the committed land outline the corridor map draws on.

**Run once, commit the output, never run in CI.** This is the same arrangement
`scripts/make_social_card.py` has: a static asset that changes about as often as
the coastline does, generated by a script that is not part of the build and whose
absence from `requirements.txt` is deliberate. It needs only the standard
library, so there is nothing to add either way.

    python scripts/make_basemap.py

**Why a committed outline rather than a map library.** The corridor map is eight
great-circle arcs from Delhi drawn in inline SVG. MapLibre would bring a tile
source, so an API key or a hosted style, on a project whose entire discipline is
that it builds offline from committed data, plus roughly 800KB of WebGL that
neither prints nor themes to the palette. Natural Earth is public domain, the
outline is 127 polygons, and a projection is two lines of arithmetic.

**Source.** Natural Earth 1:110m physical land, via the `nvkelso/natural-earth-
vector` mirror. Natural Earth is in the public domain and asks for no permission
or attribution, though attribution is recorded in `NOTICE` and
`data/data_dictionary.md` anyway, because a committed asset with no recorded
provenance is the thing this repo refuses everywhere else.

**What the simplification does and what it costs.** Coordinates are rounded to
one decimal degree, which is about 11km at the equator and invisible on a map
drawn 1100 pixels wide across 225 degrees of longitude. Points that collapse onto
each other after rounding are dropped, as are polygons whose bounding box is
smaller than a threshold, which removes small islands that would render as single
pixels. Antarctica is dropped: no corridor in this case goes near it and it is a
sixth of the file.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "web" / "public" / "geo" / "_raw_land.json"
OUT = ROOT / "web" / "public" / "geo" / "land.json"

SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
    "geojson/ne_110m_land.geojson"
)

PRECISION = 1
MIN_SPAN_DEG = 3.0  # bounding box side below which a polygon is dropped
MIN_LAT = -60.0  # Antarctica is not on any corridor in this case


def _simplify_ring(ring: list[list[float]]) -> list[list[float]]:
    """Round, then drop points that landed on top of their predecessor."""
    out: list[list[float]] = []
    for lon, lat in ring:
        point = [round(lon, PRECISION), round(lat, PRECISION)]
        if not out or point != out[-1]:
            out.append(point)
    # A ring needs to close, and needs enough points to still be a shape.
    if len(out) >= 4 and out[0] != out[-1]:
        out.append(out[0])
    return out


def build() -> dict:
    if not RAW.exists():
        raise SystemExit(
            f"missing {RAW}. Download it first:\n  curl -sL -o {RAW} {SOURCE}"
        )

    raw = json.loads(RAW.read_text(encoding="utf-8"))
    rings: list[list[list[float]]] = []

    for feature in raw["features"]:
        geometry = feature["geometry"]
        polygons = (
            [geometry["coordinates"]]
            if geometry["type"] == "Polygon"
            else geometry["coordinates"]
        )
        for polygon in polygons:
            # Outer ring only. Holes are lakes at this scale and the map is a
            # silhouette, not a physical atlas.
            ring = _simplify_ring(polygon[0])
            if len(ring) < 4:
                continue
            lons = [p[0] for p in ring]
            lats = [p[1] for p in ring]
            if max(lons) - min(lons) < MIN_SPAN_DEG and max(lats) - min(lats) < MIN_SPAN_DEG:
                continue
            if max(lats) < MIN_LAT:
                continue
            rings.append(ring)

    return {
        "source": "Natural Earth 1:110m physical land, public domain",
        "url": SOURCE,
        "note": (
            "Outer rings only, coordinates rounded to "
            f"{PRECISION} decimal degree(s), polygons under {MIN_SPAN_DEG} degrees "
            f"dropped, nothing south of {MIN_LAT}. Generated by scripts/make_basemap.py."
        ),
        "rings": rings,
    }


def main() -> int:
    data = build()
    OUT.write_text(json.dumps(data, separators=(",", ":")), encoding="utf-8")
    points = sum(len(r) for r in data["rings"])
    print(f"{OUT.relative_to(ROOT)}: {len(data['rings'])} rings, {points} points, "
          f"{OUT.stat().st_size / 1024:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
